title: My first github page
author: JimBob
email: JOwens818@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I have a description over here

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
